name: "🕷️ Hiba jelentés"
description: Hibák vagy váratlan viselkedés jelentése
labels:
- bug
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/microsoft/PowerToys/issues) before filing a new one!
- type: input
  attributes:
    label: Konverter verzió
    placeholder: 24.1.1
  validations:
    required: true

- type: dropdown
  attributes:
    label: Problémás modulok
    description: Melyik modulokkal volt probléma?
    multiple: true
    options:
      - Általános
      - Bank
      - OSA kimenő számla feldolgozás 
      - OSA bejövő számla feldolgozás
      - OPG pénztárgép adat feldolgozás
      - Adóhatósági XML-fájl feldolgozás
      - Számlázz.hu CSV-fájl feldolgozás
  validations:
    required: true

- type: textarea
  attributes:
    label: A reprodulálás lépései
    description: Javasolt kép, log fájl csatolása.
    placeholder: A hiba reprodukálásának részletes lépései
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Várt viselkedés
    placeholder: Várt viselkedés leíársa.
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Aktuális viselkedés
    placeholder: Aktuális viselkedés leírása
  validations:
    required: false

- type: textarea
  attributes:
    label: Egyéb információ
    description: Melyik könyvelő programba történt a feladás?
    placeholder: |
      UJEGYKE 2024.01
      UJEGYSZ 2024.01
      WUJEGYKE 2024.01
  validations:
    required: false
